FROM node:latest

WORKDIR /app/src

ENV NODE_PATH /usr/local/lib/node_modules
RUN yarn global add truffle
RUN yarn global add solc@0.8.9
RUN yarn global add chai
RUN yarn global add truffle-assertions
RUN yarn global add web3
RUN yarn global add chai-bn
