FROM node:latest

WORKDIR /app/src
RUN yarn global add truffle
RUN yarn global add ganache-cli

# Listening on port 8545, which is the default port of ganache
EXPOSE 8545
# TODO maybe later we need to specify networkID for ganache
# use "--networkId", "1337"
CMD ganache-cli --host=0.0.0.0 -m="${MNEMONIC}" --accounts=${AMOUNT_ADDRESS}
